### PR TITLE
Implemented basic psn info and data sending

### PR DESCRIPTION
**Pull request by m-tthw**
Basic data packing to match PSN specs. See example "simple_send_and_receive" for more details.

The multicast part is handled via the very nice [Multicast Expert for Python repo](https://github.com/multiplemonomials/multicast_expert)

Tested on Raspberry Pi OS and Mac OS (current versions).

I tried to match as much as possible your coding style, I'm open to any suggestions!

Thanks for all the previous work :)

### CODE REVIEW

**Comment by vanous** [comment]
This is awesome, thank you :) 👍

Glad to see that this package has been useful to you.

Do you mind running black or ruff on the code? Never mind if you re-format my stuff.

I have added a test to pack with your data and parse with pypsn, you can cherry-pick this commit 321d917 from https://github.com/open-stage/python-psn/tree/pr-branch  into your branch if you want :)

**Comment by m-tthw** [comment]
There you go :)

Two important changes:

1. I had to rename the var **id** to **tracker_id** in PsnTracker class to avoid redefining built-in **id** var.
2. I also renamed most of the module's classes to conform to PascalCase naming style.

I adapted all examples and tests to work with the new names.

**Comment by vanous** [comment]
For naming, what you typically do in python is CamelCase for classes, and snake_cases for methods and functions, so i would not bring too much of the Java.World.Here :)

**Comment by vanous** [comment]
OK, thank you. I will merge this now and will re-run with ruff, as i am not sure what formatter you used. I will add ruff to the CI/CD as i did for my other projects.

Thank you for all the work, much appreciated!

**Comment by m-tthw** [comment]
Okay thanks for the infos!

I had the module successfully send trackers data to GrandMa3 today. It also made me discover a few low level bugs in the function I added. What is the best way to push those fixes to your repo? Another pull request?

**Comment by m-tthw** [comment]
I'll rebase my branch on yours first and then double check before another PR :)

Thanks again for your work!

**Comment by vanous** [comment]
Awesome, thank you!
Sorry to push the `ruff` formatter later, i did not anticipate anyone contributing here.

If you need another places for testing, I was originally testing PSN with the RoboSpot and with Chataigne, it is great if you need a receiver. It is also implemented in BlenderDMX, the pypsn lib is used there.

Please do a new PR once you figure out the changes. It would be awesome if you first create a test, then you fix the issue, making the test pass, hope the initial structure i created can help you along the way.

**Pull request merged**
